# Generated by Django 5.1.1 on 2024-09-17 10:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialties',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialties',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cleaning', 'Cleaning'), ('filling', 'Filling'), ('root_canal', 'Root Canal'), ('crown', 'Crown'), ('teeth_whitening', 'Teeth Whitening')], default=[], max_length=49),
        ),
    ]
